### ISSUE TITLE
[Bug]: Adastra build command removes custom fonts

### ISSUE THREAD

**Issue by ghost** [odestry/adastra#36]
### Please confirm that you have:

- [X] Searched [existing issues](.) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://www.npmjs.com/package/adastra-cli).

### In which of these areas are you experiencing a problem?

CLI

### Expected behavior

Hi Adastra team,

I'm using Adastra for the first time on my client project. I'm using custom fonts in the assets folder, but when I run `npm run build,` the custom fonts are removed.

How can I run the build command without deleting my custom fonts?

Thanks,
Ulziibat

### Actual behavior

When I run `npm run build,` the custom fonts are removed.

### Reproduction steps

1. copy the custom fonts to the assets folder
2. npm run build
3. custom fonts are removed

### Operating System

Mac OS Monterey

### Adastra CLI version (check your project's `package.json` if you're not sure)

latest

### Shell

zsh

### Node version (run `node -v` if you're not sure)

v20.0.0

### What language and version are you using in your application?

ruby 3.0.4p208 (2022-04-12 revision 3fa771dded) [arm64-darwin21], git version 2.40.1

**Comment by benshrimpton** [comment]
@lukecharle @blanklob @creativeq-dev The problem with this `empty / not empty` flag is that for older sites that are being migrated where we absolutely HAVE to keep the assets folder content, we end up with dozen of Adastra build files in the assets folder.

<img width="280" alt="Screen Shot 2023-08-15 at 5 15 45 PM" src="https://github.com/blanklob/adastra/assets/739699/b741f995-bcfd-467e-b391-b3b798fdb51d">

Would be good if there was a `remove all old Adastra build files` feature in the build process.

**Comment by lukecharle** [comment]
I found a solution for this, thanks to Dan Gamble.

Install `@by-association-only/vite-plugin-shopify-clean` package and update `vite.config.js` to the following:

```
import { defineConfig } from 'vite';
import adastra from 'adastra-plugin';
import shopifyClean from '@by-association-only/vite-plugin-shopify-clean';

export default defineConfig({
  plugins: [
    adastra(),
    shopifyClean({
      manifestFileName: 'adastra.manifest.json'
    })
  ],
  build: {
    emptyOutDir: false
  }
});
```
